version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alexkin0520
    ports:
      - "5432:5432"
      
  redis:
    image: redis:alpine

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
